In [18]:
import torch

In [19]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [20]:
#a:copy the column,b:copy the line,finally generate 3*2 matrix
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [21]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [22]:
#index==-1:the last element,1:3--1<=index<3(left close,right open)
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [23]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
#0:2--same as the front,:--all this dimension
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [ ]:
#deep copy
before = id(Y)
Y = Y + X
id(Y) == before

False

In [26]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2442574363408
id(Z): 2442574363408


In [ ]:
#shallow copy(conserve memory space)
before = id(X)
X += Y
id(X) == before

True

In [28]:
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [29]:
a=torch.tensor([3.5])
a,a.item(),int(a),float(a)

(tensor([3.5000]), 3.5, 3, 3.5)