In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [ ]:
#均匀分布
Y = net(torch.rand(4, 8))
Y.mean()

tensor(4.6566e-10, grad_fn=<MeanBackward0>)

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.1396, -1.0215,  0.5796],
        [ 0.3922,  1.0845, -0.8010],
        [ 0.9591,  0.7511, -0.0663],
        [ 0.0219, -1.3890,  1.1674],
        [-1.5973,  1.8175, -0.2789]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))

tensor([[2.2774, 1.0063, 1.7456],
        [1.0932, 2.8531, 0.9748]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])