In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)  # when we open requires_grad,we can track the process of the tensor calculate
x.grad  # 默认值是None

In [3]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward()
#the grad is a attribute of tensor
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad == 4 * x

tensor([True, True, True, True])

In [6]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [ ]:
x.grad.zero_()
y=x*x#y is a tensor
#pytorch default:Derivative of a Scalar with Respect to a Tensor(标量对张量求导)

#equivalent to y.backward(torch.ones(len(x)))
y.sum().backward()#equivalent to scalar, converting a tensor to a scalar lets us compute gradients effortlessly
x.grad

tensor([0., 2., 4., 6.])

In [ ]:
x.grad.zero_()
y=x*x
u=y.detach()#untrack the y=x*x,u can be seen as a constant
z=u*x

z.sum().backward()
x.grad==u

tensor([True, True, True, True])

In [11]:
x.grad.zero_()
y.sum().backward()#y is not like u,y is tracked
x.grad == 2 * x

tensor([True, True, True, True])

In [ ]:
#wwe can figure out c=k*a
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [13]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward() 
a.grad == d / a

tensor(True)